apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ezeelogin-deployment
spec:
  selector:
    matchLabels:
      app: test-ezeelogin
      environment: test
    
  template:
    metadata:
      labels:
        app: test-ezeelogin
        environment: test
    spec:
      containers:
        - image: ezeelogin/ee:ezeelogin-test-0.4.0
          name: ezeeloginee
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
          env:
          - name: MONGO_URI
            value: "mongodb://admin:admin123AD@ez-mongodb-cluster.mongodb.svc.cluster.local:27017"
          # These secrets are required to start the pod.
          - name: EZ_LOG
            value: "debug"
          - name: EZSEK
            value: "Testing@1234567891"            
            
